version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mallan-mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: mallan-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  mysql_data: