spring:
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      repositories:
        enabled: false

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
