name: "🛠️ Fix"
description: '수정이 필요한 기능이나 동작이 있나요? (Jira Story와 연동됩니다.)'
labels: [fix]
title: '이슈 제목을 입력하세요'
body:
  - type: input
    id: storyKey
    attributes:
      label: '🌳 관련 Jira 키 (Story Ticket Number)'
      description: 'Jira의 Story Ticket Number를 입력해주세요 (예: ICT-102)'
      placeholder: 'EX) ICT-102'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🍃 브랜치명 (Branch)'
      description: '버그 수정을 위한 브랜치명을 작성해주세요 (예: fix/your-bug)'
      placeholder: 'fix/your-bug'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: '🔧 수정할 내용'
      description: 어떤 부분을 어떻게 수정할 예정인지 작성해주세요.
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: '📋 작업 항목'
      description: 수정에 필요한 작업 단계를 나열해주세요.
    validations:
      required: false

  - type: textarea
    id: etc
    attributes:
      label: '📌 기타'
      description: 전달할 내용이 있다면 작성해주세요.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **🔗 자동 생성된 정보**
        - Jira Story: `${{ inputs.storyKey }}`
