spring:
  config:
    import: optional:file:.env.properties, classpath:application-${spring.profiles.active}.yml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  docker:
    compose:
      enabled: false


springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method