spring:
  config:
    import: optional:file:.env.properties, classpath:application-local.yml
  profiles:
    active: local

  docker:
    compose:
      enabled: false


springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method