name: Deploy to cloudtype
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: yujeongran/mallan
          stage: main
          yaml: |
            name: mallan
            app: dockerfile
            options:
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: deploy
                - name: POSTGRES_HOST
                  value: postgres
                - name: POSTGRES_PORT
                  value: "5432"
                - name: POSTGRES_DB
                  value: mallan
                - name: POSTGRES_USER
                  value: mallanuser
                - name: POSTGRES_PASSWORD
                  value: mallanpass
                - name: REDIS_HOST
                  value: redis
                - name: REDIS_PORT
                  value: "6379"
              args: []
              ports: "8080"
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
